### ISSUE TITLE
Offsets Changed RIP Dotka

### ISSUE THREAD

**Issue by snajdovski** [shekeru/dotka-cheats#4]
Offsets probably changed or moved, it crashes when Injected :(
Could you point out how I can find these offsets again I could try but I have no exp with IDA or CE

**Comment by darksoul577** [comment]
The crash is when it tries to load the vgui2 module. vgui2.dll does not seem to be loaded. see for yourself- you can even delete vgui2.dll and dota will still run fine.

if you comment out the lines for loading the vgui2.dll it'll run without crashing. it's not a big deal if you can't use vgui2's paint traverse function, you can just replace that with directx hooks to do the same thing.

the main issue is that the virtual functions are a little off. there's been a couple of additions in the past year. so the calls to the functions in the CBaseCombatCharacter.h, CBaseEntity.h, CBaseFlex.h, CDotaBaseNPC.h, and so forth will cause crashes. it's too bad because the classes are 99% of the way there, just a little off. For example, if you run the first virtual function SchemaDynamicBinding().binding name, it correctly tells you the name of an entity that was added or removed. 

I tried figuring out the missing virtual function calls in IDA (with the class informer plugin) to get this project working again, but haven't been able to get that working. Maybe Shekeru can tell us how he was able to figure out all those virtual function calls so we can fix it.

**Comment by Eastonn** [comment]
> The crash is when it tries to load the vgui2 module. vgui2.dll does not seem to be loaded. see for yourself- you can even delete vgui2.dll and dota will still run fine.
You need to start the game with this launch setting -console, otherwise the module does not load.

**Comment by snajdovski** [comment]
Yeah I found the cause too, now works but I have a other problem I got VAC banned using other Injector (Extreme Injector) anyhow after changing the injector it seemed to fix the issue somehow.
Other issue I have found is when I try to open the console I get an instant crash. I saw in the code that there is disable console function commented out but the same issue persists.

**Comment by darksoul577** [comment]
I got great feedback in another post for how to fix the offsets:

https://github.com/LWSS/McDota/issues/48#issuecomment-631898195

Basically by comparing the virtual function calls with the ones in the MAC binary (2016) that included full debugging information.
